title: Atman Darji
subtitle: The official website of Atman J Darji
description: >- # this means to ignore newlines until "baseurl:"
  This website contains all the professional information about Atman Darji

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: Contact Me
      url : /contact

# Edit these details

author_logo: profile.png
author: Atman Darji
author_bio: Software Development Engineer and Computer Science Lover!
author_email: "atman.darji@gmail.com"
author_location: India
author_website_url: "http://atdarji.xyz"

author_work_experiences:
            - company_name: Clarisights
              company_logo: clarisights.png
              company_url: https://clarisights.com
              designation: Software Engineer
              description: Worked as a backend engineer at Clarisights
              visibility: true

author_education_details:
              - college_logo: daiict.png
                college_name: DAIICT
                college_url: https://daiict.ac.in
                college_degree: ICT Engineer
                description: Bachelor of Technology
                visibility: true

author_project_details:
              - project_thumbnail: flapai.png
                project_title: FlapAI Bird
                project_description: A flappy bird learning to fly with help of neuro evolution.
                project_url: https://atmandarji.github.io/FlappyLearning/
                visibility: true

# social links
twitter_username: atdarji
github_username:  atmandarji
facebook_username: atmandarji
linkedin_username: atmandarji
instagram_username: atdarji

#for comments using disqus
disqus_shortname: atman-darji

# formspree (contact form)
formspree_email: atman.darji@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
